services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: SITH-PHP
    image: php:8.2-apache
    ports:
      - "6680:80"  # Accessible to other devices on the network
    volumes:
      - .:/var/www/html  # Mount PHP files from the current directory
    restart: unless-stopped
    networks:
      - public
    depends_on:
      - mysql

  mysql:
    # Using MariaDB is fully compatible with MySQL client libraries (like the one used in db_publisher)
    image: mariadb:latest 
    container_name: SITH-MySQL
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SITH
      MYSQL_USER: SITH
      MYSQL_PASSWORD: SITH
    volumes:
      - SITH-mysql-data:/var/lib/mysql
      - ./init_scripts:/docker-entrypoint-initdb.d
    command: --binlog-format=ROW --log-bin=mysql-bin --server-id=1
    ports:
      - "6606:3306"

    networks:
      - public

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: SITH-PHPMyAdmin
    environment:
      PMA_HOST: mysql # Link to the MariaDB container service name
      MYSQL_ROOT_PASSWORD: rootpassword # Use the same root password as MariaDB
      PMA_PORT: 3306 # MariaDB's internal port
    ports:
      - "6681:80" # Expose phpMyAdmin on host port 6681
    depends_on:
      - mysql # Use the service name
    networks:
      - public

  mosquitto:
    image: eclipse-mosquitto:latest 
    container_name: SITH-MQTT-Broker
    ports:
      - "6683:1883" # MQTT standard port
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      TZ: "Australia/Sydney" # Set your timezone
    networks:
      - public # Ensure it's on the same network as db_publisher

  # Custom DB-to-MQTT Publisher
  db_publisher:
    build: 
      context: ./db_publisher_app
      dockerfile: Dockerfile
    container_name: SITH-DB-Publisher
    restart: unless-stopped
    depends_on:
      - mysql
      - mosquitto
    environment:
      DB_HOST: SITH-MySQL
      DB_NAME: SITH
      DB_USER: SITH
      DB_PASS: SITH
      MQTT_HOST: SITH-MQTT-Broker
      MQTT_PORT: 6683
      POLL_INTERVAL_SECONDS: 5
    volumes:
      - SITH-db_publisher_data:/app
    networks:
      - public

    

volumes:
  SITH-mysql-data:
  SITH-db_publisher_data:

networks:
  public:
    driver: bridge
  private:
    internal: true # No external access